POST  http://localhost:3001/api/categories
Content-Type: application/json

{
    "categoryName" : "Warlike - Drama"
}

###

POST  http://localhost:3001/api/categories
Content-Type: application/json

{
    "categoryName" : "Horror"
}
