POST  http://localhost:3001/api/movies
Content-Type: application/json

{
    "name" : "The darkest hours",
    "director" : "Joe Wrigth",
    "category" : {
                    "id": "60c99ad507379748a41e73c2",
                    "categoryName": "Science - Fiction"
                 }
}

###

POST  http://localhost:3001/api/movies
Content-Type: application/json

{
    "name" : "IT: Primera parte",
    "director" : "Andy Muschietti",
    "category" : {
                    "id": "60c9c82738dc3c37a0b7a7b2",
                    "categoryName": "Science - Fiction"
                 }
}

###
POST  http://localhost:3001/api/movies
Content-Type: application/json

{
    "name" : "IT: Primera parte",
    "category" : {
                    "id": "60c9c82738dc3c37a0b7a7b2",
                    "categoryName": "Science - Fiction"
                 }
}

###

POST  http://localhost:3001/api/movies
Content-Type: application/json

{
    "director" : "Andy Muschietti",
    "category" : {
                    "id": "60c9c82738dc3c37a0b7a7b2",
                    "categoryName": "Science - Fiction"
                 }
}
###
POST  http://localhost:3001/api/movies
Content-Type: application/json

{
    "name" : "Interstellar",
    "director" : "Christopher Nolan",
    "category" : {
                    "id":"60cbb9c8b5f60a39d87eacfc",
                    "categoryName": "Science - Fiction"
                 }

}