DELETE http://localhost:3001/api/categories/60cacbea962d400015f8f627

###

DELETE http://localhost:3001/api/categories/5

###

DELETE http://localhost:3001/api/categories/60cacbea962d400015f8f629
###

DELETE http://localhost:3001/api/categories/60cd4cc4b5f60b0015078fc5